## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10,41)
arr2 = np.arange(220,251)

arr3 = arr1 + arr2
arr3

array([230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290])

2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [3]:
new_arr = np.arange(100, 170).reshape(10, 7)
new_arr

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [4]:
e_arr = np.arange(2, 51, 2)
o_arr = np.arange(1, 51, 2)
m_arr = e_arr * o_arr

m_arr

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [5]:
arr = np.random.randint(1,1000, size=(40, 5))
arr

array([[368, 346, 804,  22,  23],
       [680, 485, 390, 984, 401],
       [609, 616, 510,  50, 586],
       [943, 264,  74, 470, 108],
       [325,  79,  48, 970, 101],
       [206, 738, 338, 259, 109],
       [200, 377, 789, 928, 809],
       [245, 892, 673, 714, 788],
       [853, 170, 710, 883,  19],
       [499, 637, 800, 837, 688],
       [313,  45, 439, 521, 867],
       [638, 766, 270, 153,  39],
       [826, 186, 863, 317, 706],
       [783, 959,  61, 338, 955],
       [ 21, 687,  41, 851, 310],
       [972, 220, 486, 266, 125],
       [318, 462, 537, 574, 959],
       [268, 714, 468, 245, 735],
       [310, 547, 347, 499, 937],
       [324, 671,  39, 987, 461],
       [559, 879, 208, 987, 752],
       [947, 298, 990,   4, 290],
       [126, 367,   6, 552, 830],
       [289, 251,  66, 717, 251],
       [ 81, 120, 191, 689, 363],
       [403, 422,  55, 947, 743],
       [721, 399, 820, 427, 862],
       [366, 152, 879, 613, 429],
       [521, 215, 825, 434, 552],
       [496, 4

In [6]:
arr[(arr % 2 == 0) & (arr % 5 == 0)]

array([680, 390, 510,  50, 470, 970, 200, 170, 710, 800, 270, 310, 220,
       310, 990, 290, 830, 120, 820, 760,  60, 590, 180])